{% set name = "binlets" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/binlets-{{ version }}.tar.gz
  sha256: 1f2fd2190adad145cdf5c56029248ddec4448e07cb16ac03d36276f146913c31

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - numpy
    - typing-extensions

test:
  imports:
    - binlets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maurosilber/binlets
  summary: Denoising via adaptive binning.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maurosilber
